{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tailscale-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tailscale-injector.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow webhook calls from API server
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: {{ .Values.webhook.port }}
  # Allow metrics scraping from monitoring namespace
  {{- if .Values.networkPolicy.allowMetrics }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.monitoringNamespace }}
    ports:
    - protocol: TCP
      port: {{ .Values.webhook.metricsPort }}
  {{- end }}
  # Allow health checks from same namespace
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.webhook.healthPort }}
  egress:
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow Kubernetes API access
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          component: kube-apiserver
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow access to Kubernetes API server via service
  - to:
    - namespaceSelector:
        matchLabels:
          name: default
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTPS to external services (Tailscale control plane)
  {{- if .Values.networkPolicy.allowExternalTraffic }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 169.254.0.0/16
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
{{- end }}