{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tailscale-injector.serviceAccountName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

---
# Minimal ClusterRole with least privilege principle
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tailscale-injector.fullname" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
rules:
# Minimal permissions for webhook operation
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

# Read-only access to admission webhook configurations for self-monitoring
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list"]

# Event creation for audit trail
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tailscale-injector.fullname" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tailscale-injector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale-injector.serviceAccountName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}

{{- if .Values.rbac.namespaced }}
---
# Additional namespace-scoped permissions for secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tailscale-injector.fullname" . }}-secrets
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailscale-injector.fullname" . }}-secrets
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tailscale-injector.fullname" . }}-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale-injector.serviceAccountName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
{{- end }}

{{- if .Values.rbac.pspEnabled }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "tailscale-injector.fullname" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tailscale-injector.fullname" . }}-psp
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - {{ include "tailscale-injector.fullname" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tailscale-injector.fullname" . }}-psp
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tailscale-injector.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale-injector.serviceAccountName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
{{- end }}
{{- end }}