{{- if and .Values.authKey.create .Values.authKey.value (not .Values.authKey.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale-injector.authKeySecretName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: auth
  {{- with (include "tailscale-injector.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.authKey.secretKey }}: {{ .Values.authKey.value | b64enc }}
{{- end }}