apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale-injector.webhookServiceName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: webhook
  {{- with (include "tailscale-injector.serviceAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: webhook-api
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  {{- if .Values.metrics.enabled }}
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: {{ .Values.metrics.port }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "tailscale-injector.selectorLabels" . | nindent 4 }}
    component: webhook

{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale-injector.metricsServiceName" . }}
  namespace: {{ include "tailscale-injector.namespace" . }}
  labels:
    {{- include "tailscale-injector.labels" . | nindent 4 }}
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/path: "/metrics"
    {{- with (include "tailscale-injector.annotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: {{ .Values.metrics.port }}
    protocol: TCP
  selector:
    {{- include "tailscale-injector.selectorLabels" . | nindent 4 }}
    component: webhook
{{- end }}